version: "1"
rules:
  - base: master
    upstream: ProfElements:master
    mergeMethod: merge
    conflictReviewers:
      - weiii-joe
      - xMikux
      - xwinhyukx
  - base: master
    upstream: Slimefun-Addon-Community:master
    mergeMethod: merge
    conflictReviewers:
      - weiii-joe
      - xMikux
      - xwinhyukx
